### ISSUE TITLE
docker.sock for Windows support 

### ISSUE THREAD

**Issue by unickq** [aerokube/cm#85] opened 2017-10-13 13:44 UTC
Add ability to mount **docker.sock** for Windows with double slashes:

`-v //var/run/docker.sock:/var/run/docker.sock`

Works with _Docker for Windows 17.06_.
Validated with already configured browsers.json
`docker run --rm -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v "%dir_with_selenoidConfig%:/etc/selenoid" aerokube/selenoid:latest-release start`

**Comment by vania-pooh** [comment] 2017-10-13 14:24
This is related to #81.

**Comment by vania-pooh** [comment] 2018-01-09 13:23
Duplicate of #117.

**Closed by vania-pooh** 2018-01-09 13:23 UTC
