### ISSUE TITLE
Selenoid image is not downloaded

### ISSUE THREAD

**Issue by rekby** [aerokube/cm#58] opened 2017-07-19 06:02 UTC
```
DOCKER_API_VERSION=1.24 ./cm_1.2.1 version
Git Revision: 1.2.1
UTC Build Time: 2017-07-17_09:51:06AM

[root@localhost ~]# DOCKER_API_VERSION=1.24 ./cm_1.2.1 selenoid start
2017/07/19 09:02:03 Using Docker...
2017/07/19 09:02:03 registry.ping url=https://registry.hub.docker.com/v2/
2017/07/19 09:02:05 Downloading Selenoid...
2017/07/19 09:02:05 Fetching tags for image "aerokube/selenoid"...
2017/07/19 09:02:05 registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
2017/07/19 09:02:06 Trying to pull repository docker.io/aerokube/selenoid ... :
2017/07/19 09:02:08 Pulling from docker.io/aerokube/selenoid: latest-release
2017/07/19 09:02:08 Digest: sha256:32f6fb08178398a18f3b19e98b40cd8fb8e49941c527bf74045714f6df10cd66: latest-release
2017/07/19 09:02:08 Selenoid is already configured
2017/07/19 09:02:08 Starting Selenoid...
2017/07/19 09:02:08 Failed to start: Selenoid image is not downloaded: this is probably a bug
```

**Comment by aandryashin** [comment] 2017-07-19 06:06
You have to clean up previous state:

$ DOCKER_API_VERSION=1.24 ./cm_1.2.1 selenoid cleanup

and then:

$ DOCKER_API_VERSION=1.24 ./cm_1.2.1 selenoid start

2017-07-19 9:02 GMT+03:00 Timofey Koolin <notifications@github.com>:

**Comment by rekby** [comment] 2017-07-19 06:33
[root@localhost ~]# DOCKER_API_VERSION=1.24 ./cm_1.2.1 selenoid cleanup
2017/07/19 09:08:46 Using Docker...
2017/07/19 09:08:46 registry.ping url=https://registry.hub.docker.com/v2/
2017/07/19 09:08:48 Selenoid is not running
2017/07/19 09:08:48 Successfully removed configuration directory


[root@localhost ~]# DOCKER_API_VERSION=1.24 ./cm_1.2.1 selenoid cleanup
2017/07/19 09:08:46 Using Docker...
2017/07/19 09:08:46 registry.ping url=https://registry.hub.docker.com/v2/
2017/07/19 09:08:48 Selenoid is not running
2017/07/19 09:08:48 Successfully removed configuration directory
[root@localhost ~]# DOCKER_API_VERSION=1.24 ./cm_1.2.1 selenoid start
2017/07/19 09:09:18 Using Docker...
2017/07/19 09:09:18 registry.ping url=https://registry.hub.docker.com/v2/
2017/07/19 09:09:20 Downloading Selenoid...
2017/07/19 09:09:20 Fetching tags for image "aerokube/selenoid"...
2017/07/19 09:09:20 registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
2017/07/19 09:09:22 Trying to pull repository docker.io/aerokube/selenoid ... :
2017/07/19 09:09:24 Pulling from docker.io/aerokube/selenoid: latest-release
2017/07/19 09:09:24 Digest: sha256:32f6fb08178398a18f3b19e98b40cd8fb8e49941c527bf74045714f6df10cd66: latest-release
2017/07/19 09:09:24 Configuring Selenoid...
2017/07/19 09:09:24 Processing browser "firefox"...
2017/07/19 09:09:24 Fetching tags for image "selenoid/firefox"...
2017/07/19 09:09:24 registry.tags url=https://registry.hub.docker.com/v2/selenoid/firefox/tags/list repository=selenoid/firefox
2017/07/19 09:09:25 Pulling image "selenoid/firefox:54.0"...
2017/07/19 09:09:25 Trying to pull repository docker.io/selenoid/firefox ... :
2017/07/19 09:09:27 Pulling from docker.io/selenoid/firefox: 54.0
2017/07/19 09:09:27 Digest: sha256:a02a7558748da61720276d23edc8360ca18c2921f1593bcc992678b02e21402c: 54.0
2017/07/19 09:09:27 Pulling image "selenoid/firefox:53.0"...
2017/07/19 09:09:27 Trying to pull repository docker.io/selenoid/firefox ... :
2017/07/19 09:09:29 Pulling from docker.io/selenoid/firefox: 53.0
2017/07/19 09:09:29 Digest: sha256:5a4e4a6dfa423cddee9cb3f85d08ac93660284f69fb09a0a30f9953e676089e4: 53.0
2017/07/19 09:09:29 Processing browser "chrome"...
2017/07/19 09:09:29 Fetching tags for image "selenoid/chrome"...
2017/07/19 09:09:29 registry.tags url=https://registry.hub.docker.com/v2/selenoid/chrome/tags/list repository=selenoid/chrome
2017/07/19 09:09:30 Pulling image "selenoid/chrome:59.0"...
2017/07/19 09:09:30 Trying to pull repository docker.io/selenoid/chrome ... :
2017/07/19 09:09:32 Pulling from docker.io/selenoid/chrome: 59.0
2017/07/19 09:09:32 Digest: sha256:e08cbe17e5c50317056819f6e1a6487772caa01dc6309899f661e1a27fdb6b8e: 59.0
2017/07/19 09:09:32 Pulling image "selenoid/chrome:58.0"...
2017/07/19 09:09:32 Trying to pull repository docker.io/selenoid/chrome ... :
2017/07/19 09:09:34 Pulling from docker.io/selenoid/chrome: 58.0
2017/07/19 09:09:34 Digest: sha256:e624734a79f694b53cd06ae0160312a96c0790b7f09aed862b0b556a03b2755e: 58.0
2017/07/19 09:09:34 Processing browser "opera"...
2017/07/19 09:09:34 Fetching tags for image "selenoid/opera"...
2017/07/19 09:09:34 registry.tags url=https://registry.hub.docker.com/v2/selenoid/opera/tags/list repository=selenoid/opera
2017/07/19 09:09:35 Pulling image "selenoid/opera:46.0"...
2017/07/19 09:09:35 Trying to pull repository docker.io/selenoid/opera ... :
2017/07/19 09:09:37 Pulling from docker.io/selenoid/opera: 46.0
2017/07/19 09:09:37 Digest: sha256:32e01029a915222b83eb2fc51a820b131ede5c5dba2f60deff753318f3c869cf: 46.0
2017/07/19 09:09:37 Pulling image "selenoid/opera:45.0"...
2017/07/19 09:09:37 Trying to pull repository docker.io/selenoid/opera ... :
2017/07/19 09:09:39 Pulling from docker.io/selenoid/opera: 45.0
2017/07/19 09:09:39 Digest: sha256:54ad7dd12f378c8661af0b572b34affcb1d33bc018d9add759118840338eb4df: 45.0
2017/07/19 09:09:39 Successfully saved configuration to /root/.aerokube/selenoid/browsers.json
2017/07/19 09:09:39 Starting Selenoid...
2017/07/19 09:09:39 Failed to start: Selenoid image is not downloaded: this is probably a bug

I tried complete remove .aerokube and all docker images
[root@localhost ~]# rm -rf .aerokube/
[root@localhost ~]# for i in `docker images -q`; do docker rmi $i; done

then start
DOCKER_API_VERSION=1.24 ./cm_1.2.1 selenoid start

It fails with same result

**Comment by rekby** [comment] 2017-07-19 06:38
docker images now:

REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
docker.io/selenoid/opera      46.0                57ef879acaca        3 weeks ago         659.4 MB
docker.io/aerokube/selenoid   latest-release      93ee78105aa5        4 weeks ago         12.88 MB
docker.io/selenoid/firefox    54.0                16c76a9611e6        4 weeks ago         596.8 MB
docker.io/selenoid/chrome     59.0                69f2765a857b        5 weeks ago         715.1 MB
docker.io/selenoid/opera      45.0                8d0081974280        9 weeks ago         620.4 MB
docker.io/selenoid/firefox    53.0                603932e78430        10 weeks ago        712 MB
docker.io/selenoid/chrome     58.0                366d993edd78        3 months ago        649.8 MB

**Comment by vania-pooh** [comment] 2017-07-19 07:49
Hmm... Very interesting. It should not download `latest-release`, only an exact version. Seems to be a bug.

**Comment by vania-pooh** [comment] 2017-07-19 18:53
@rekby could you also please copy the output of:
```
# docker inspect aerokube/selenoid:latest-release
```

**Comment by rekby** [comment] 2017-07-20 04:40
```
[root@localhost ~]# docker inspect aerokube/selenoid:latest-release
[
    {
        "Id": "sha256:93868437854477ab0b6c14dc3cfc930fad89a8367663caab9198cde9980c9480",
        "RepoTags": [
            "docker.io/aerokube/selenoid:latest-release"
        ],
        "RepoDigests": [
            "docker.io/aerokube/selenoid@sha256:cfd14f1142111d106d0598d5298677445c172427f5ed75a937b6ad81c6b4b150"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-07-19T13:07:19.41012841Z",
        "Container": "27d423aac40a926f64535fe7ec51932eee638c404b2e3056d6e6842d1d5c0d13",
        "ContainerConfig": {
            "Hostname": "3009dd4da609",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4444/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/usr/bin/selenoid\" \"-listen\" \":4444\" \"-conf\" \"/etc/selenoid/browsers.json\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:7ddd18a1b1265ee0a5f9eea5a4dc23faadec95300a4b12bd5a36aba36a1913d2",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/selenoid",
                "-listen",
                ":4444",
                "-conf",
                "/etc/selenoid/browsers.json"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "17.03.1-ce",
        "Author": "",
        "Config": {
            "Hostname": "3009dd4da609",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4444/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "sha256:7ddd18a1b1265ee0a5f9eea5a4dc23faadec95300a4b12bd5a36aba36a1913d2",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/selenoid",
                "-listen",
                ":4444",
                "-conf",
                "/etc/selenoid/browsers.json"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 13036124,
        "VirtualSize": 13036124,
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "97",
                "DeviceName": "docker-253:0-153142-18f13fabe40866d09838d0d01dc34440847b7b247e81aaceeeafd2816fd8a2e3",
                "DeviceSize": "10737418240"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:040fd7841192c4f283485d5c7817f4508a774a8fabef8fc265c87f4d2a2ae635",
                "sha256:efdc8457ea9bdef3010102cdb0b18ab8060b034f73a7ce5dcd722759fbe127a1",
                "sha256:27ad58802f65c8849230eac6e4f43da6be52475e059a2de435b49b60b1a4ac55"
            ]
        }
    }
]
```

**Comment by vania-pooh** [comment] 2017-07-20 05:03
@rekby: ok, I fixed the issue with downloading latest-release but still don't get why you get `Selenoid image is not downloaded: this is probably a bug` error. I would like to build a development version of `cm` so you could test it. Are you using Mac or Linux to run `cm`?

**Comment by rekby** [comment] 2017-07-20 05:59
I use linux, clean centos 7 + docker

**Comment by vania-pooh** [comment] 2017-07-20 06:30
Please try again with this binary (zipped because otherwise Github is refusing to upload the file).
[cm_linux_amd64.zip](https://github.com/aerokube/cm/files/1161363/cm_linux_amd64.zip)

**Comment by rekby** [comment] 2017-07-20 06:59
same error

```
[root@localhost ~]# ./cm_linux_amd64 version
Git Revision: HEAD
UTC Build Time: unknown
[root@localhost ~]# ./cm_linux_amd64 selenoid start
2017/07/20 09:59:04 Using Docker...
2017/07/20 09:59:04 registry.ping url=https://registry.hub.docker.com/v2/
2017/07/20 09:59:06 Downloading Selenoid...
2017/07/20 09:59:06 Fetching tags for image "aerokube/selenoid"...
2017/07/20 09:59:06 registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
2017/07/20 09:59:07 Trying to pull repository docker.io/aerokube/selenoid ... :
2017/07/20 09:59:09 Pulling from docker.io/aerokube/selenoid: 1.3.3
2017/07/20 09:59:09 Digest: sha256:cfd14f1142111d106d0598d5298677445c172427f5ed75a937b6ad81c6b4b150: 1.3.3
2017/07/20 09:59:09 Selenoid is already configured
2017/07/20 09:59:09 Starting Selenoid...
2017/07/20 09:59:09 Failed to start: Selenoid image is not downloaded: this is probably a bug

```

**Comment by vania-pooh** [comment] 2017-07-20 07:02
Ok. Let me try to reproduce myself. At least the issue with `latest-release` is fixed.

**Comment by vania-pooh** [comment] 2017-07-20 12:58
Can not reproduce. Tried with the same binary as you and the following environment.
```
[root@9218d654fe40 /]# docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
555f200a940f        aerokube/selenoid:1.3.3   "/usr/bin/selenoid..."   7 seconds ago       Up 3 seconds        0.0.0.0:4444->4444/tcp   selenoid
[root@9218d654fe40 /]# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@9218d654fe40 /]# uname -a
Linux 9218d654fe40 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@9218d654fe40 /]# rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64
[root@9218d654fe40 /]# docker logs selenoid
2017/07/20 12:53:03 Loading configuration files...
2017/07/20 12:53:03 Loaded configuration from [/etc/selenoid/browsers.json]
2017/07/20 12:53:03 Using default containers log configuration because of: read error: open config/container-logs.json: no such file or directory
2017/07/20 12:53:03 Timezone: UTC
2017/07/20 12:53:03 Listening on :4444
```
I just started `centos:7` in privileged Docker container, then installed Docker inside according to instructions: https://docs.docker.com/engine/installation/linux/docker-ce/centos/#install-using-the-repository, then typed: `./cm selenoid start`. Please type `# docker version` and check that your API version corresponds to what you are specifying to `cm`.

**Comment by vania-pooh** [comment] 2017-07-21 11:04
@rekby any updates?

**Comment by rekby** [comment] 2017-07-21 16:09
I'm without computer now. I will check and update isdue in 1-2 days.
-------- Исходное сообщение --------От: Ivan Krutov <notifications@github.com> Дата: 21.07.17  14:04  (GMT+03:00) Кому: aerokube/cm <cm@noreply.github.com> Копия: Timofey Koolin <timofey@koolin.ru>, Mention <mention@noreply.github.com> Тема: Re: [aerokube/cm] Selenoid image is not downloaded (#58) 
@rekby any updates?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aerokube/cm","title":"aerokube/cm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aerokube/cm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vania-pooh in #58: @rekby any updates?"}],"action":{"name":"View Issue","url":"https://github.com/aerokube/cm/issues/58#issuecomment-316973359"}}}

**Comment by rekby** [comment] 2017-07-22 11:04
I have error in my centos7 environments (without docker).
At home I try it in virtualbox.

For debug purpose I have created public VDS Centos 7, I have sended credentials for access to VDS by email.

It is test VDS - I doesn't need anything into it - you can do anything what you want to debug selenoid.

**Comment by vania-pooh** [comment] 2017-07-22 18:14
I can confirm that this is reproducing on your VM. Investigating it.

**Comment by vania-pooh** [comment] 2017-07-22 18:41
Here is the new `cm` binary. 
[cm.zip](https://github.com/aerokube/cm/files/1167547/cm.zip) Just by running `cm selenoid start` with this binary you are getting Selenoid container started but failing to load `browsers.json` because of `permission denied for /etc/selenoid/browsers.json`. The latter issue is a SELinux one (https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker) and I just typed `su -c "setenforce 0"` and it started. So now your VM contains running and working Selenoid. Please test again but I think the issue is fixed.

**Comment by rekby** [comment] 2017-07-23 05:53
Yes, it is work with disabled selinux.

And after initialization with setenforce 0 it will start after enable selinux and reboot.
I think selinux deny somethink on initialization only?

Can you try to run docker with :z or :Z mount option option (man docker-run, search by :z) for work containers with enabled selinux?

**Comment by vania-pooh** [comment] 2017-07-23 07:54
I think instead of trying to add some hacks to `cm` code you just need to remove `--selinux-enabled` flag from Docker globally.

**Comment by rekby** [comment] 2017-07-24 03:58
I think it is addition, but not hack.
with :z you allow to use external files by containers, it is normal flag for docker mount.

exec 'setenforce 0' from cm - is hack, add mount option I think - good.

In my scenario it isn't important - I can compete disable selinux or use debian or something else - the VDS may be dedicated for selenoid.
But I think it will good for other users who will start selenoid in centos.

**Comment by vania-pooh** [comment] 2017-07-24 11:21
After discussing this stuff with guys I can state that "permission denied" is distribution specific Docker issue. In order to be as simple as possible and distribution-agnostic `cm` should not contain such specific hacks. Closing for the moment. But this can be reopened if more facts come into play.

**Closed by vania-pooh** 2017-07-24 11:21 UTC
Labels: bug
